-- =====================================================================
-- DEPRECATED: see ./migrations/ instead.
-- =====================================================================
-- This file is kept for backwards compatibility. New schema changes go
-- into supabase/migrations/ as numbered SQL files. Apply migrations in
-- order (0001 -> 0002 -> ...) via the Supabase SQL editor.
--
-- For first-time setup, run all of these in order:
--   1. migrations/0001_init.sql            (schema)
--   2. migrations/0002_seed_products.sql   (sample data, optional)
--   3. migrations/0003_admin_rbac.sql      (admin role + policies)
--   4. migrations/0004_stripe_event_log.sql (webhook idempotency)
--   5. migrations/0005_inventory_function.sql (inventory functions)
--
-- See ./db.md for the post-setup runbook (creating the first admin,
-- registering webhooks, etc.).
-- =====================================================================
